onlineStore/myauth/urls.py
from django.contrib.auth.views import LoginView, PasswordChangeView, LogoutView
from django.urls import path

from .views import index, RegisterView, ProfileView, ProfileEditView, ProfileDeleteView, ChatView

app_name = 'myauth'
urlpatterns = [
    path('', index, name='main'),
    path('login/', LoginView.as_view(
        template_name='myauth/login.html',
        redirect_authenticated_user=True
    ), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/edit/', ProfileEditView.as_view(), name='edit'),
    path('profile/<int:pk>/change_password/',
         PasswordChangeView.as_view(template_name="myauth/profile_change_password.html"), name='change_password'),
    path('profile/<int:pk>/delete/', ProfileDeleteView.as_view(), name='delete'),
    path('profile/<int:pk>/chat/', ChatView.as_view(), name='chat'),
    path('profile/exit/', LogoutView.as_view(), name='exit'),
]

onlineStore/onlineStore/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from onlineStore import settings

urlpatterns = [
    path('', include('myauth.urls')),
    path('shop/', include('shop.urls')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

onlineStore/shop/urls.py
from django.urls import path

from .views import ProductListView, CreateProductView, ProductDetailsView, ProductDeleteView, CartDetailsView, \
    AddProductToCartView, DeleteProductFromCartView, CartClearView, BuyView, ProductEditView

app_name = 'shop'
urlpatterns = [
    path('products/', ProductListView.as_view(), name='products'),
    path('products/product/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/product/<int:pk>/edit/', ProductEditView.as_view(), name='product_edit'),
    path('products/product/<int:pk>/add_to_cart/', AddProductToCartView.as_view(), name='add_product_to_cart'),
    path('products/product/<int:pk>/delete_from_cart/', DeleteProductFromCartView.as_view(),
         name='delete_product_from_cart'),
    path('products/product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('create/', CreateProductView.as_view(), name='create_product'),
    path('cart/', CartDetailsView.as_view(), name='cart'),
    path('cart/clear/', CartClearView.as_view(), name='cart_clear'),
    path('buy/', BuyView.as_view(), name='buy')
]

onlineStore/shop/models.py
from django.contrib.auth.models import User
from django.db import models


def product_preview_directory_path(instance: 'Product', filename: str) -> str:
    return 'products/product_{pk}/preview/{filename}'.format(pk=instance.pk, filename=filename)


class Product(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    count = models.IntegerField(default=10)
    image = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products')
    customers = models.ManyToManyField(User, related_name='cart')

onlineStore/shop/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, AccessMixin
from django.contrib.auth.models import User
from django.db.models import Sum
from django.http import HttpResponse, Http404, HttpResponseNotFound
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView

from shop.models import Product


class AddProductToCartView(LoginRequiredMixin, AccessMixin, View):
    def check(self, pk):
        return Product.objects.filter(pk=pk).exists() and self.request.user != Product.objects.get(pk=pk).user

    def get(self, request, pk):
        if not self.check(pk):
            self.handle_no_permission()
        product = get_object_or_404(Product, pk=pk)
        request.user.cart.add(product)
        return redirect(reverse('shop:products'))


class DeleteProductFromCartView(LoginRequiredMixin, AccessMixin, View):
    def check(self, pk):
        return Product.objects.filter(pk=pk).exists() and self.request.user.cart.filter(pk=pk).exists()

    def get(self, request, pk):
        if not self.check(pk):
            self.handle_no_permission()
        product = get_object_or_404(Product, pk=pk)
        request.user.cart.remove(product)
        return redirect(reverse('shop:cart'))


class ProductListView(ListView):
    template_name = 'shop/products.html'
    context_object_name = 'products'
    queryset = Product.objects.filter(archived=False)
    paginate_by = 3


class CreateProductView(LoginRequiredMixin, CreateView):
    model = Product
    template_name = 'shop/create_product.html'
    fields = 'name', 'description', 'price', 'discount', 'count', 'image'
    success_url = reverse_lazy('shop:products')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProductEditView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        product = self.get_object()
        return self.request.user == product.user

    model = Product
    template_name = 'shop/product_edit.html'
    context_object_name = 'product'
    fields = 'name', 'description', 'price', 'discount', 'count', 'image'

    def get_success_url(self):
        return reverse('shop:product_details', kwargs={'pk': self.object.pk})


class ProductDetailsView(DetailView):
    model = Product


class ProductDeleteView(UserPassesTestMixin, DeleteView):
    def test_func(self):
        product = self.get_object()
        return self.request.user == product.user

    model = Product
    success_url = reverse_lazy('shop:products')


class CartDetailsView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'shop/cart_detail.html'

    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super(CartDetailsView, self).get_context_data(**kwargs)
        context['bill'] = self.request.user.cart.aggregate(Sum('price')).get('price__sum')
        return context


class CartClearView(LoginRequiredMixin, View):
    def get(self, request):
        request.user.cart.clear()
        return redirect(reverse('shop:cart'))


class BuyView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'shop/buy.html')

    def post(self, request):
        for product in request.user.cart.all():
            product.count -= 1
            if product.count == 0:
                product.archived = True
            product.save()
        request.user.cart.clear()
        return redirect(reverse('shop:products'))

onlineStore/shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'shop/base.css' %}">
    {% block css %}

    {% endblock %}
</head>
<body>
<header class="site-header">
    <nav class="main-nav">
        <ul class="nav-list">
            {% if not request.user.is_authenticated %}
                <li><a href="{% url 'myauth:login' %}" class="nav-link">Вход</a></li>
                <li><a href="{% url 'myauth:register' %}" class="nav-link">Регистрация</a></li>
            {% endif %}
            <li><a href="{% url 'shop:products' %}" class="nav-link">Товары</a></li>
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'myauth:profile' request.user.id %}" class="nav-link">Личный кабинет</a></li>
                <li><a href="{% url 'shop:cart' %}" class="nav-link">Корзина</a></li>
            {% endif %}
        </ul>
    </nav>
</header>
<main class="main-content">
    {% block main %}

    {% endblock %}
</main>
<footer class="site-footer">
    Copyright Fimuje 2023
</footer>
</body>
</html>

onlineStore/shop/templates/shop/buy.html
{% extends 'shop/base.html' %}

{% block title %}
    Подтверждение покупки
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/buy.css' %}">
{% endblock %}


{% block main %}
    <h1>
        Подтверждение покупки
    </h1>
    <div class="purchase-confirmation">
        <h1 class="confirmation-title">Вы уверены, что хотите оформить покупку?</h1>
        <br>
        <div class="back-link">
            <a href="{% url 'shop:cart' %}" class="back-link">Назад</a>
        </div>
        <br>
        <div class="confirmation-form">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="confirm-purchase-btn">Оформить покупку</button>
            </form>
        </div>
    </div>
{% endblock %}

onlineStore/shop/templates/shop/cart_detail.html
{% extends 'shop/base.html' %}

{% block title %}
    Корзина пользователя {{ user.username }}
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/cart.css' %}">
{% endblock %}

{% block main %}
    <h1>
        Корзина пользователя {{ user.username }}
    </h1>
    {% if user.cart.all %}
        <p><a href="{% url 'shop:cart_clear' %}" class="cart-action">Очистить корзину</a></p>
        <h1 class="page-title">Товары</h1>
        <ul class="product-list">
            {% for product in user.cart.all %}
                <div class="product-item">
                    <p class="product-name">Название: <a
                            href="{% url 'shop:product_details' product.pk %}">{{ product.name }}</a></p>
                    <p class="product-price">Цена: {{ product.price }}$</p>
                    <p><a href="{% url 'shop:delete_product_from_cart' product.pk %}" class="cart-action">Удалить из
                        корзины</a></p>
                </div>
            {% endfor %}
        </ul>
        <p class="total-price">К оплате {{ bill|floatformat:2 }}$</p>
        <p><a href="{% url 'shop:buy' %}" class="cart-action">Купить</a></p>
    {% else %}
        <p class="empty-cart">Корзина пуста!</p>
    {% endif %}
{% endblock %}

onlineStore/shop/templates/shop/create_product.html
{% extends 'shop/base.html' %}

{% block title %}
    Создать товар
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/create_product.css' %}">
{% endblock %}

{% block main %}
    <h1>Создать товар</h1>
    <div class="create-product-form">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="create-product-btn">Создать</button>
        </form>
    </div>
    <p><a href="{% url 'shop:products' %}" class="back-link">Назад</a></p>
{% endblock %}

onlineStore/shop/templates/shop/product_confirm_delete.html
{% extends 'shop/base.html' %}

{% block title %}
    Подтверждение удаления {{ object.name }}
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/product_confirm_delete.css' %}">
{% endblock %}

{% block main %}
    <h1 class="confirmation-title">Вы уверены, что хотите удалить товар {{ object.name }}?</h1>
    <br>
    <div class="confirmation-back-link">
        <a href="{% url 'shop:product_details' object.pk %}" class="back-link">Back</a>
    </div>
    <br>
    <div class="confirmation-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="confirm-delete-btn">Удалить</button>
        </form>
    </div>
{% endblock %}

onlineStore/shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}

{% block title %}
    Товар {{ product.name }}
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/product_detail.css' %}">
{% endblock %}

{% block main %}
    <h1>Товар {{ product.name }}</h1>
    <div class="product-details">
        <p class="product-name">Название: {{ product.name }}</p>
        <p class="product-description">Описание: {{ product.description }}</p>
        <p class="product-price">Цена: {{ product.price }}$</p>
        <p class="product-discount">Скидка: {{ product.discount }}%</p>
        <p class="product-count">Количество: {{ product.count }} шт.</p>
        <p class="product-image">
            {% if product.image %}
                <img src="{{ product.image.url }}" alt="{{ product.image.name }}" class="product-img">
            {% endif %}
        </p>
        <p class="product-owner">Владелец: <a href="{% url 'myauth:profile' product.user.id %}" class="owner-link">{{ product.user }}</a></p>
    </div>
    <div class="product-actions">
        {% if request.user == product.user %}
            <p><a href="{% url 'shop:product_edit' product.pk %}" class="edit-product-link">Редактировать товар</a></p>
            <p><a href="{% url 'shop:product_delete' product.pk %}" class="delete-product-link">Удалить товар</a></p>
        {% endif %}
        <p><a href="{% url 'shop:products' %}" class="back-link">Назад</a></p>
    </div>
{% endblock %}

onlineStore/shop/templates/shop/product_edit.html
{% extends 'shop/base.html' %}

{% block title %}
    Редактирование товара {{ product.name }}
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/product_edit.css' %}">
{% endblock %}

{% block main %}
    <div class="product-edit">
        <h1 class="edit-title">Редактирование товара {{ product.name }}</h1>
        <div class="edit-form">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save-button">Сохранить</button>
            </form>
        </div>
        <div class="back-link">
            <p><a href="{% url 'shop:product_details' product.id %}" class="back-link">Назад</a></p>
        </div>
    </div>
{% endblock %}

onlineStore/shop/templates/shop/products.html
{% extends 'shop/base.html' %}

{% block title %}
    Товары
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/products.css' %}">
{% endblock %}

{% block main %}
    <h1>Товары</h1>
    <ul class="product-list">
        {% for product in page_obj %}
            <li class="product-item">
                <div>
                    <p class="product-name">Название: <a href="{% url 'shop:product_details' product.pk %}">{{ product.name }}</a></p>
                    <p class="product-description">Описание: {{ product.description }}</p>
                    <p class="product-price">Цена: {{ product.price }}$</p>
                    {% if request.user.is_authenticated and product.user != request.user %}
                        <p><a href="{% url 'shop:add_product_to_cart' product.pk %}" class="cart-action">Добавить в корзину</a></p>
                    {% endif %}
                </div>
            </li>
        {% endfor %}
    </ul>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1" class="page-link">&laquo; первая</a>
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">предыдущая</a>
            {% endif %}

            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="page-link">следующая</a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">последняя &raquo;</a>
            {% endif %}
        </span>
    </div>
    <div>
        {% if request.user.is_authenticated %}
            <p><a href="{% url 'shop:create_product' %}" class="create-product-link">Создать товар</a></p>
        {% endif %}
    </div>
{% endblock %}