onlineStore/myauth/urls.py
from django.contrib.auth.views import LoginView, PasswordChangeView, LogoutView
from django.urls import path

from .views import index, RegisterView, ProfileView, ProfileEditView, ProfileDeleteView, ChatView

app_name = 'myauth'
urlpatterns = [
    path('', index, name='main'),
    path('login/', LoginView.as_view(
        template_name='myauth/login.html',
        redirect_authenticated_user=True
    ), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/edit/', ProfileEditView.as_view(), name='edit'),
    path('profile/<int:pk>/change_password/',
         PasswordChangeView.as_view(template_name="myauth/profile_change_password.html"), name='change_password'),
    path('profile/<int:pk>/delete/', ProfileDeleteView.as_view(), name='delete'),
    path('profile/<int:pk>/chat/', ChatView.as_view(), name='chat'),
    path('profile/exit/', LogoutView.as_view(), name='exit'),
]

onlineStore/onlineStore/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from onlineStore import settings

urlpatterns = [
    path('', include('myauth.urls')),
    path('shop/', include('shop.urls')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

onlineStore/shop/urls.py
from django.urls import path

from .views import ProductListView, CreateProductView, ProductDetailsView, ProductDeleteView, CartDetailsView, \
    AddProductToCartView, DeleteProductFromCartView, CartClearView, BuyView, ProductEditView

app_name = 'shop'
urlpatterns = [
    path('products/', ProductListView.as_view(), name='products'),
    path('products/product/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/product/<int:pk>/edit/', ProductEditView.as_view(), name='product_edit'),
    path('products/product/<int:pk>/add_to_cart/', AddProductToCartView.as_view(), name='add_product_to_cart'),
    path('products/product/<int:pk>/delete_from_cart/', DeleteProductFromCartView.as_view(),
         name='delete_product_from_cart'),
    path('products/product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('create/', CreateProductView.as_view(), name='create_product'),
    path('cart/', CartDetailsView.as_view(), name='cart'),
    path('cart/clear/', CartClearView.as_view(), name='cart_clear'),
    path('buy/', BuyView.as_view(), name='buy')
]

onlineStore/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


class Dialog(models.Model):
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='dialogs_user1')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='dialogs_user2')

    def get_partner_for(self, user):
        if user == self.user1:
            return self.user2
        elif user == self.user2:
            return self.user1


class Message(models.Model):
    dialog = models.ForeignKey(Dialog, on_delete=models.CASCADE, related_name='messages')
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

onlineStore/myauth/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin, AccessMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from myauth.models import Dialog, Message


def index(request):
    return render(request, 'myauth/index.html')


class RegisterView(CreateView):
    template_name = 'myauth/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('myauth:main')

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(
            self.request,
            username=username,
            password=password
        )
        login(request=self.request, user=user)
        return response


class ChatView(LoginRequiredMixin, AccessMixin, View):
    def get(self, request, pk):
        user1 = get_object_or_404(User, pk=pk)
        user2 = request.user
        if user1 == user2:
            self.handle_no_permission()
        if Dialog.objects.filter(user1=user1, user2=user2).exists():
            dialog = Dialog.objects.get(user1=user1, user2=user2)
        elif Dialog.objects.filter(user2=user1, user1=user2).exists():
            dialog = Dialog.objects.get(user1=user2, user2=user1)
        else:
            dialog = Dialog.objects.create(user1=user1, user2=user2)
        return render(request, 'myauth/chat.html', context={'dialog': dialog})

    def post(self, request, pk):
        user1 = get_object_or_404(User, pk=pk)
        user2 = request.user
        if user1 == user2:
            self.handle_no_permission()
        if Dialog.objects.filter(user1=user1, user2=user2).exists():
            dialog = Dialog.objects.get(user1=user1, user2=user2)
        else:
            dialog = Dialog.objects.get(user1=user2, user2=user1)
        Message.objects.create(sender=user2, content=request.POST['message'], dialog=dialog)
        return redirect(reverse('myauth:chat', kwargs={'pk': pk}))


class ProfileView(DetailView):
    model = User
    template_name = 'myauth/profile.html'
    context_object_name = 'user'


class ProfileEditView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        user = self.get_object()
        return self.request.user == user

    model = User
    template_name = 'myauth/profile_edit.html'
    context_object_name = 'user'
    fields = 'username', 'first_name', 'last_name', 'email'

    def get_success_url(self):
        return reverse('myauth:profile', kwargs={'pk': self.object.pk})


class ProfileDeleteView(UserPassesTestMixin, DeleteView):
    def test_func(self):
        user = self.get_object()
        return self.request.user == user

    model = User
    success_url = reverse_lazy('myauth:main')
    template_name = 'myauth/profile_confirm_delete.html'

onlineStore/myauth/templates/myauth/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'myauth/base.css' %}">
    {% block css %}

    {% endblock %}
</head>
<body>
<header class="site-header"> <!-- Добавлен класс для стилизации -->
    <nav class="main-nav"> <!-- Добавлен класс для стилизации -->
        <ul class="nav-list"> <!-- Добавлен класс для стилизации -->
            {% if not request.user.is_authenticated %}
                <li><a href="{% url 'myauth:login' %}" class="nav-link">Вход</a></li>
                <li><a href="{% url 'myauth:register' %}" class="nav-link">Регистрация</a></li>
            {% endif %}
            <li><a href="{% url 'shop:products' %}" class="nav-link">Товары</a></li>
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'myauth:profile' request.user.id %}" class="nav-link">Личный кабинет</a></li>
                <li><a href="{% url 'shop:cart' %}" class="nav-link">Корзина</a></li>
            {% endif %}
        </ul>
    </nav>
</header>
<main class="main-content"> <!-- Добавлен класс для стилизации -->
    {% block main %}

    {% endblock %}
</main>
<footer class="site-footer"> <!-- Добавлен класс для стилизации -->
    Copyright Fimuje 2023
</footer>
</body>
</html>

onlineStore/myauth/templates/myauth/chat.html
{% extends 'myauth/base.html' %}

{% block title %}
    Чат с пользователем {{ user.username }}
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'myauth/chat.css' %}">
{% endblock %}

{% block main %}
    <h1>Чат с пользователем {{ user.username }}</h1>
    <div class="chat-messages">
        <ul>
            {% for message in dialog.messages.all %}
                <li class="message {% if message.sender == request.user %}sent{% else %}received{% endif %}">
                    <p class="sender-name"><a
                            href="{% url 'myauth:profile' message.sender.pk %}">{{ message.sender }}</a></p>
                    <p class="message-content">{{ message.content }}</p>
                    <p class="message-time">{{ message.created_at|date:'Y-m-d H:i' }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="chat-form">
        <form method="post">
            {% csrf_token %}
            <input type="text" name="message" class="message-input" placeholder="Введите сообщение">
            <input type="submit" value="Отправить" class="send-button">
        </form>
    </div>
{% endblock %}

onlineStore/myauth/templates/myauth/index.html
{% extends 'myauth/base.html' %}

{% block title %}
    Главная страница
{% endblock %}

{% block main %}
    Добро пожаловать в онлайн-магазин!
{% endblock %}

onlineStore/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Аутентификация
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'myauth/login.css' %}">
{% endblock %}

{% block main %}
    <h1>Аутентификация</h1>
    <div class="authentication-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="login-button">Войти</button>
        </form>
    </div>
{% endblock %}

onlineStore/myauth/templates/myauth/profile.html
{% extends 'myauth/base.html' %}

{% block title %}
    Профиль пользователя {{ user.username }}
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'myauth/profile.css' %}">
{% endblock %}

{% block main %}
    <h1>Профиль пользователя {{ user.username }}</h1>
    <div class="user-profile">
        <p class="profile-label">Никнейм:</p>
        <p class="profile-info">{{ user.username }}</p>
        <p class="profile-label">Имя:</p>
        <p class="profile-info">{{ user.first_name }}</p>
        <p class="profile-label">Фамилия:</p>
        <p class="profile-info">{{ user.last_name }}</p>
        <p class="profile-label">Email:</p>
        <p class="profile-info">{{ user.email }}</p>
    </div>
    {% if user == request.user %}
        <p><a href="{% url 'myauth:edit' user.id %}" class="profile-action">Редактировать данные</a></p>
        <p><a href="{% url 'myauth:change_password' user.id %}" class="profile-action">Сменить пароль</a></p>
        <p><a href="{% url 'myauth:delete' user.id %}" class="profile-action">Удалить аккаунт</a></p>
        <p><a href="{% url 'myauth:exit' %}" class="profile-action">Выйти из аккаунта</a></p>
    {% else %}
        <p><a href="{% url 'myauth:chat' user.id %}" class="profile-action">Написать сообщение</a></p>
    {% endif %}
{% endblock %}

onlineStore/myauth/templates/myauth/profile_change_password.html
{% extends 'myauth/base.html' %}

{% block title %}
    Смена пароля пользователя {{ user.username }}
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'myauth/profile_change_password.css' %}">
{% endblock %}

{% block main %}
    <h1>Смена пароля пользователя {{ user.username }}</h1>
    <div class="change-password-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save-button">Сохранить</button>
        </form>
    </div>
    <p><a href="{% url 'myauth:profile' user.id %}" class="back-link">Назад</a></p>
{% endblock %}

onlineStore/myauth/templates/myauth/profile_confirm_delete.html
{% extends 'shop/base.html' %}

{% block title %}
    Подтверждение удаления пользователя {{ object.username }}
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'myauth/profile_confirm_delete.css' %}">
{% endblock %}

{% block main %}
    <div class="delete-user-confirmation">
        <h1 class="confirmation-title">Вы уверены, что хотите удалить свой аккаунт?</h1>
        <br>
        <div class="back-link">
            <a href="{% url 'myauth:profile' object.pk %}" class="back-link">Назад</a>
        </div>
        <br>
        <div class="confirmation-form">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="confirm-delete-btn">Удалить</button>
            </form>
        </div>
    </div>
{% endblock %}

onlineStore/myauth/templates/myauth/profile_edit.html
{% extends 'myauth/base.html' %}

{% block title %}
    Редактирование профиля пользователя {{ user.username }}
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'myauth/profile_edit.css' %}">
{% endblock %}

{% block main %}
    <h1>
        Редактирование профиля пользователя {{ user.username }}
    </h1>
    <div class="edit-profile-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save-button">Сохранить</button>
        </form>
    </div>
    <p><a href="{% url 'myauth:profile' user.id %}" class="back-link">Назад</a></p>
{% endblock %}

onlineStore/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Регистрация
{% endblock %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'myauth/register.css' %}">
{% endblock %}

{% block main %}
    <h1>
        Регистрация
    </h1>
    <div class="registration-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Зарегистрироваться" class="register-button">
        </form>
    </div>
{% endblock %}